// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qutadbcjqvnvyckhorfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dGFkYmNqcXZudnlja2hvcmZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjI0MTgsImV4cCI6MjA2MDQ5ODQxOH0.OPfPKDQ1sF4vjq_xOnh5rmgewQ5YZrM799O0Ew1tRtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);